# Generated by Django 4.1.7 on 2023-03-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='english', max_length=100),
            preserve_default=False,
        ),
    ]
