# Generated by Django 4.1.7 on 2023-03-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='n',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
