# Generated by Django 4.1.7 on 2023-03-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_bookmark_geeksmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookmark',
            field=models.ManyToManyField(to='main_app.bookmark'),
        ),
    ]
